owner: areebahmeddd
repo: care_uptime

sites:
  # Production
  - name: Landing
    url: https://ohc.network
  - name: Care
    url: https://care.ohc.network
  - name: Care API
    url: https://careapi.ohc.network
  - name: Documentation
    url: https://docs.ohc.network
  - name: Leaderboard
    url: https://contributors.ohc.network
  - name: School
    url: https://school.ohc.network

status-website:
  cname: status.areeb.dev
  name: Open Healthcare Network Uptime
  logoUrl: https://cdn.ohc.network/care_logo.svg
  favicon: https://github.com/ohcnetwork/care_fe/blob/develop/public/favicon.ico
  introTitle: "Welcome to the OHC Network Status Page"
  introMessage: Monitor the uptime and performance of key services across the Open Healthcare Network. For questions or issues, please [contact us](mailto:support@ohc.network).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/ohcnetwork

assignees:
  - areebahmeddd
